name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  checks: write

jobs:
  unit-tests-backend:
    runs-on: ubuntu-latest
    outputs:
      coverage: ${{ steps.test-backend.outputs.report }}
    steps:
      - uses: actions/checkout@v4
      - name: set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"
          cache-dependency-path: bugtracker-backend/go.sum

      - name: install go-junit-report
        run: go install github.com/jstemmer/go-junit-report/v2@latest

      - name: execute backend unit test
        id: test-backend
        working-directory: ./bugtracker-backend
        run: |
          go test -coverprofile=coverage.out -covermode=atomic ./...
          go tool cover -func=coverage.out > coverage.txt
          
          echo "## Go test coverage report" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          cat coverage.txt >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          
          echo "report<<EOF" >> $GITHUB_OUTPUT
          cat coverage.txt >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
          
          go test ./... -v 2>&1 | go-junit-report > test-results.xml

      - name: publish backend tests results
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: backend unit tests report
          path: bugtracker-backend/test-results.xml
          reporter: jest-junit

  unit-tests-frontend:
    runs-on: ubuntu-latest
    outputs:
      coverage: ${{ steps.test-frontend.outputs.report }}
    steps:
      - uses: actions/checkout@v4

      - name: setup node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: bugtracker-frontend/package-lock.json

      - name: execute frontend unit test
        id: test-frontend
        working-directory: ./bugtracker-frontend
        run: |
          npm ci
          npm test | tee full_output.txt
          
          echo "## frontend coverage report" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          cat full_output.txt >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          
          echo "report<<EOF" >> $GITHUB_OUTPUT
          cat full_output.txt >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: publish frontend test results
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: frontend tests report
          path: bugtracker-frontend/test-results.xml
          reporter: jest-junit

  create-coverage-comment:
    if: github.event_name == 'pull_request'
    needs: [unit-tests-backend, unit-tests-frontend]
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: create backend coverage comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ## Backend Test Coverage Report
            
            ```
            ${{ needs.unit-tests-backend.outputs.coverage }}
            ```
      - name: create frontend coverage comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ## Frontend Test Coverage Report
            
            ```
            ${{ needs.unit-tests-frontend.outputs.coverage }}
            ```
            
            

  api-e2e-performance-tests:
    needs: [unit-tests-backend, unit-tests-frontend]
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: launch app
        run: |
          docker compose up --build -d
          npx wait-port http://localhost:8080/api/health -t 30000      

      - name: run api tests
        working-directory: ./tests-api
        run: |
          npm ci
          npx playwright test

      - name: run e2e tests
        working-directory: ./tests-e2e
        env:
          CI: "1"
        run: |
          npm ci
          npx playwright install
          npx playwright test

      - name: setup k6
        uses: grafana/setup-k6-action@v1

      - name: run performance test
        uses: grafana/setup-k6-action@v1
        with:
          path: tests-perf/script.js
          flags: --out json=summary.json

      - name: turn down app
        run: |
          docker compose down

      - name: upload api tests results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: api-test-results
          path: ./tests-api/test-results/

      - name: upload api tests playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: api-test-playwright-report
          path: ./tests-api/playwright-report/

      - name: upload e2e tests results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: e2e-test-results
          path: ./tests-e2e/tests-results/

      - name: upload e2e tests playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: e2e-test-playwright-report
          path: ./tests-e2e/playwright-report/

      - name: upload performance raw results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: performance-raw-results
          path: ./tests-perf/summary.json

      - name: upload performance HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: performance-report
          path: perf-results.html

      - name: publish api tests results
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: api-test-report
          path: ./tests-api/test-results/*.xml
          reporter: jest-junit

      - name: publish e2e tests results
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: e2e-test-report
          path: ./tests-e2e/test-results/results.xml
          reporter: jest-junit